version: "3"

volumes:
  swapvid_ui_node_modules: # Volume Trick

services:
  swapvid_ui:
    image: taichimurakami/swapvid_frontend
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: swapvid_frontend
    volumes:
      - ./app:/app
      - swapvid_ui_node_modules:/app/node_modules
    ports:
      - 3070:3070
    tty: true
    stdin_open: true
    init: true
    command: /bin/sh -c "cd /app && npm run dev"
